version: '3'

services:
  influxdb:
    image: quay.io/influxdb/influxdb3-core:latest
    container_name: influxdb
    volumes:
      - ${PATH_IN_HOST_MACHINE}:/influxdb-data
    ports:
      - "127.0.0.1:8181:8181"
    command: >
      serve
      --node-id beach_banana
      --object-store file
      --data-dir /influxdb-data
      --without-auth

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
