version: '3'

# Define environment variables that can be used across services
x-environment: &common-env
  INFLUXDB_DATABASE: ${INFLUXDB_DATABASE:-CityWeather}

services:
  influxdb:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: influxdb
    volumes:
      - ${PATH_IN_HOST_MACHINE}:/influxdb-data
      - ./influxdb-init.sh:/influxdb-init.sh
    ports:
      - "127.0.0.1:8181:8181"
    environment:
      <<: *common-env
    entrypoint: ["/influxdb-init.sh"]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    environment:
      <<: *common-env
